### ISSUE TITLE
Not able to render on Colab

### ISSUE THREAD

**Issue by Vibha111094** [alexpashevich/E.T.#1]
The below command:

**python -m alfred.gen.render_trajs** 

works when i run it on my personal laptop, but does not seem to work on colab.

Are there any changes I can do so that I can get it working on colab.

**Comment by alexpashevich** [comment]
Hi Vibha,

To render the trajectories, you need to have an X server running. By default, the code uses `0` for the X server display number and you can change it with [`args.x_display`](https://github.com/alexpashevich/E.T./blob/master/alfred/gen/render_trajs.py#L42). We never tried to run the code with colab but you can try to do it by making sure that an X server is running at your backend device. It should be easier if you chose your local machine as a backend and check that an X server running (e.g. with `xdpyinfo`).

Best,
Alex
