### ISSUE TITLE
Stuck while rendering trajectory and Error in trying evaluation task

### ISSUE THREAD

**Issue by Samuel-Fipps** [alexpashevich/E.T.#10]
These issues are present in the current repo.

How to fix them:
Issue 1: Stuck while rendering trajectory:
https://github.com/alexpashevich/E.T./issues/8
One of the modules in requirements.txt need to be a older version. I don't remember which.  

Issue 2: Error in trying evaluation task:
https://github.com/alexpashevich/E.T./issues/6
Happens when using cuda
You can either comment it out in model.util, I think you can add .cpu() to the cuda tensor like so: feat_extracted = feat_extracted.cpu()

**Comment by Samuel-Fipps** [comment]
If I get time to make a clean repo and test out some fixes I'll make a pull request.

**Comment by alexpashevich** [comment]
Hi @Samuel-Fipps ,

Thank you for reporting the issues with the code. It is possible that one of the dependencies got updated and the newest version is not compatible with the repo anymore. I would really appreciate a pull request if you have time to do it later. If you could specify more precisely which line and file causes the second problem, I will be happy to update it in the repo.

Best,
Alex

**Comment by Samuel-Fipps** [comment]
Okay yeah, if i get time i'll look into it.  It might take a week, sorry
for the inconvenience.

**Comment by Samuel-Fipps** [comment]
Okay i think the problem is:
pip install Werkzeug==2.0.3

**Comment by Samuel-Fipps** [comment]
And that version of werkzeug needs Flask==2.1.1
I am positive this is the problem

**Comment by alexpashevich** [comment]
The issue is resolved in the [PR#12](https://github.com/alexpashevich/E.T./pull/12).
