### ISSUE TITLE
Unable to download the pretrained checkpoints

### ISSUE THREAD

**Issue by xfgao** [alexpashevich/E.T.#13]
I was not able to download the pretrained checkpoints using the following command:
```
wget http://pascal.inrialpes.fr/data2/apashevi/et_checkpoints.zip
```

**Comment by Samuel-Fipps** [comment]
It seems the AWS server they were using went down.

**Comment by alexpashevich** [comment]
Hi,

Thank you for letting us know! It looks like the server was temporary down and it works again now.

Best,
Alex

**Comment by jiminsun** [comment]
Hi Alex,

I have been facing the same issue with the wget command resulting in a 403 error.
Would it be possible to check whether the server is running?

Best,
Jimin

**Comment by littleTT0704** [comment]
Hi Jimin,

I'm not sure when they will be able to fix their file server, but I happend to download the checkpoints file.
It can be found at [here](https://drive.google.com/file/d/1-FB3VbxUrhxzW87gnheNyxBWbcIa1ErA/view?usp=sharing)

**Comment by jiminsun** [comment]
Hi @littleTT0704 thank you for sharing the checkpoint!
