### ISSUE TITLE
Evaluating only sub-goals

### ISSUE THREAD

**Issue by tejas1995** [alexpashevich/E.T.#14]
I am trying to evaluate the pre-trained ET checkpoint on only the individual sub-goals, but am currently running into issues. Here is the command I ran:
```
$ python -m alfred.eval.eval_agent with eval.exp=pretrained \
          eval.checkpoint=et_human_pretrained.pth \
          eval.object_predictor=$ET_LOGS/pretrained/maskrcnn_model.pth \
          exp.num_workers=5 \
          eval.eval_range=None \
          exp.data.valid=lmdb_human\
          eval.subgoals=all
```
The only change I added from the [command](https://github.com/alexpashevich/E.T.#pretrained-models-evaluation) in the README is the `eval.subgoals=all` argument.
However, this eventually results in this error:

```
   File "/home/caisplusplus/tejas/ET/alfred/utils/eval_util.py", line 331, in load_language
    feat_numpy = dataset.load_features(*feat_args)
TypeError: load_features() takes 2 positional arguments but 4 were given
```

The error appears to be due to [this](https://github.com/alexpashevich/E.T./blob/master/alfred/utils/eval_util.py#L330) line of code: when `subgoal_idx` is not None, it sends four arguments (including self) to [this](https://github.com/alexpashevich/E.T./blob/master/alfred/data/zoo/alfred.py#L48), which can only take two arguments. The `AlfredDataset.load_features` method does not seem to be defined to handle another `subgoal_idx`-related argument. 

Is there some error here, or should I be running this script differently?

**Comment by alexpashevich** [comment]
Hi Tejas,

Thank you for pointing at the problem. I have [pushed a fix](https://github.com/alexpashevich/E.T./commit/0d5d0e9bbd61cb0c81f33859b360004d79afa280) of this issue so I am closing it.

Best,
Alex
