### ISSUE TITLE
Trajectories were skipped

### ISSUE THREAD

**Issue by ptwaixingren** [alexpashevich/E.T.#4]
Thank you @alexpashevich for your great work
When I followed your guide to create **an LMDB dataset with natural language annotations**. It always report the error "string indices must b integers" in line 145 of the thor_env.py. The action "LookUp" seems not be an integer. This error would cause 7080 trajectories ere skipped. Would you like to tell us how to fixed it?

**Comment by alexpashevich** [comment]
Hi @ptwaixingren ,

Please check which version of ai2thor you have. It should be `ai2thor==2.1.0`. Let me know if it is already the case and I can take a closer look at your issue.

Best,
Alex

**Comment by ptwaixingren** [comment]
Thank you @alexpashevich for your information. I update the ai2thor edition to 2.1.0 according to your reply. The LMDB dataset can be generated. I also have a question about the configuration of the **args.x_display** in Note#1. My computer has two 2080TI GPUs, shall I set **args.x_display=2** or other values?

**Comment by alexpashevich** [comment]
Hi @ptwaixingren,

The `x_display` variable should be set accordingly to the X server running on your machine. Typically it is something like `:0.0` and should correspond to the `$DISPLAY` variable. If you have several X servers running, I may need to modify the code to use all of them.

Best,
Alex
