### ISSUE TITLE
Error in trying evaluation task

### ISSUE THREAD

**Issue by jeje910** [alexpashevich/E.T.#6]
Thank you for your great  work! @alexpashevich

Your paper was very interesting for me and i'm now trying to run your code in my local. But I have an issue when I try to run alfred.eval.eval_agent.

When I try to run the pretrained models evaluation code
`python3 -m alfred.eval.eval_agent with eval.exp=pretrained eval.checkpoint=et_human_pretrained.pth eval.object_predictor=$ET_LOGS/pretrained/maskrcnn_model.pth exp.num_workers=5 eval.eval_range=None exp.data.valid=lmdb_human`
FileNotFoundError came out and I cannot find which one is wrong.
The codes before this line were correctly run and worked well.

The picture below is the error I am currently suffer from.
![ET Question](https://user-images.githubusercontent.com/64236071/141687783-48829b74-1324-4f4e-a05f-6472e793bc29.png)

And the pretrained directory looks as follow.
![ET ERROR2](https://user-images.githubusercontent.com/64236071/141687907-c84af8d9-8842-4e6f-9acc-852896e4bfe2.png)

Should I copy the directory from somewhere or did I miss something before evaluate task?

Sorry for the poor question..

**Comment by jeje910** [comment]
The question above were solved by reinstalling all the data. (worker00 ~ worker03 directories were not created when i ran create_lmdb.py. So I divided the line 58 in create_lmdb.py into two, which generates the worker directories and feats directories)

But, evaluation task is not still working with the error named "AssertionError: feature extraction is not the same for training and evaluation".And this error lead to the FileNotFoundError again even if I trained the model in my own once again.
Does it mean feature extraction not worked well? And if so, what should I check to fix it..?

**Comment by jeje910** [comment]
I got this error. In model.util, it closes torch if feature extraction is different. In my case, the device lead to close torch, means tensor(0.6196, deice='cuda:0') != tensor(0.6196). It worked well when i just change my device or just comment out the assertion line. Sorry for the poor question and i'll close this issue. It works well for me now!

**Comment by alexpashevich** [comment]
@jeje910 Hi Jaeyeon. Thank you for taking a closer look and reporting which issue you encountered. Good luck with your research!

**Comment by Samuel-Fipps** [comment]
Thank you I had the same problem

**Comment by Samuel-Fipps** [comment]
> create_lmdb

Do you mine sharing how you "So I divided the line 58 in create_lmdb.py into two". Thank you!

**Comment by Samuel-Fipps** [comment]
Never mind it just returns the wrong error when it should be this error that you had:

"I got this error. In model.util, it closes torch if feature extraction is different. In my case, the device lead to close torch, means tensor(0.6196, deice='cuda:0') != tensor(0.6196). It worked well when i just change my device or just comment out the assertion line. Sorry for the poor question and i'll close this issue. It works well for me now!"

**Comment by Samuel-Fipps** [comment]
fix by adding this .cpu()

    assert torch.isclose(feat_extracted.mean().cpu(), feats_orig[0].mean()), \
        'feature extraction is not the same for training and evaluation'

**Comment by ByZ0e** [comment]
> I got this error. In model.util, it closes torch if feature extraction is different. In my case, the device lead to close torch, means tensor(0.6196, deice='cuda:0') != tensor(0.6196). It worked well when i just change my device or just comment out the assertion line. Sorry for the poor question and i'll close this issue. It works well for me now!

Sorry, I got the same mistake. And I do comment out the assertion lines:
```
assert torch.isclose(feat_extracted.mean(), feats_orig[0].mean()), \
     'feature extraction is not the same for training and evaluation'
```
But I still got the fileNotFoundError, how do I fix it? Any suggestions, please.
