### ISSUE TITLE
lack of file causes difficulty to reproduce the result

### ISSUE THREAD

**Issue by hcscctv** [alexpashevich/E.T.#7]
$ cd $ET_DATA
$ sh download_data.sh json_feat

i cannot find the download_data.sh

**Comment by alexpashevich** [comment]
Hi,

Thank you for interest in our work. The download script is [located in the ALFRED repository](https://github.com/askforalfred/alfred/blob/master/data/download_data.sh). I have [uploaded the file to the E.T. repo](https://github.com/alexpashevich/E.T./commit/92ee2378d596b55f05e5c1949726577a64215f04) as well to avoid future confusion.

Best wishes,
Alex
